/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cems;

/**
 *
 * @author PC
 */
public class createEvent extends javax.swing.JFrame {

    private String[] args;

    /**
     * Creates new form CreateEvent
     */
    public createEvent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DBlue_panel1 = new javax.swing.JPanel();
        DBlue_panel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        event_table = new javax.swing.JTable();
        organizer_new = new javax.swing.JButton();
        organizer_edit = new javax.swing.JButton();
        organizer_delete = new javax.swing.JButton();
        organzier_viewstudents = new javax.swing.JButton();
        organizer_poster = new javax.swing.JButton();
        DBlue_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DBlue_panel3 = new javax.swing.JPanel();
        createEvent_title = new javax.swing.JTextField();
        createEvent_location = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        createEvent_category = new javax.swing.JComboBox<>();
        createEvent_type = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        createEvent_dateTime = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        createEvent_submit = new javax.swing.JButton();
        createEvent_cancel = new javax.swing.JButton();

        DBlue_panel1.setBackground(new java.awt.Color(98, 98, 130));

        DBlue_panel2.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout DBlue_panel2Layout = new javax.swing.GroupLayout(DBlue_panel2);
        DBlue_panel2.setLayout(DBlue_panel2Layout);
        DBlue_panel2Layout.setHorizontalGroup(
            DBlue_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        DBlue_panel2Layout.setVerticalGroup(
            DBlue_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        event_table.setAutoCreateRowSorter(true);
        event_table.setBackground(new java.awt.Color(20, 20, 20));
        event_table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        event_table.setForeground(new java.awt.Color(255, 255, 255));
        event_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Events", "Event type", "Location", "Date & Time: Begin/End", "Participants"
            }
        ));
        event_table.setFocusable(false);
        jScrollPane1.setViewportView(event_table);

        organizer_new.setBackground(new java.awt.Color(37, 55, 30));
        organizer_new.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        organizer_new.setForeground(new java.awt.Color(255, 255, 255));
        organizer_new.setText("Create new event");
        organizer_new.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        organizer_edit.setBackground(new java.awt.Color(37, 55, 30));
        organizer_edit.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        organizer_edit.setForeground(new java.awt.Color(255, 255, 255));
        organizer_edit.setText("Edit event");
        organizer_edit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        organizer_delete.setBackground(new java.awt.Color(37, 55, 30));
        organizer_delete.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        organizer_delete.setForeground(new java.awt.Color(255, 255, 255));
        organizer_delete.setText("Delete event");
        organizer_delete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        organzier_viewstudents.setBackground(new java.awt.Color(102, 51, 0));
        organzier_viewstudents.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        organzier_viewstudents.setForeground(new java.awt.Color(255, 255, 255));
        organzier_viewstudents.setText("View registered students");
        organzier_viewstudents.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        organizer_poster.setBackground(new java.awt.Color(102, 0, 51));
        organizer_poster.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        organizer_poster.setForeground(new java.awt.Color(255, 255, 255));
        organizer_poster.setText("Upload poster");
        organizer_poster.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout DBlue_panel1Layout = new javax.swing.GroupLayout(DBlue_panel1);
        DBlue_panel1.setLayout(DBlue_panel1Layout);
        DBlue_panel1Layout.setHorizontalGroup(
            DBlue_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DBlue_panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DBlue_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DBlue_panel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(DBlue_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DBlue_panel1Layout.createSequentialGroup()
                        .addGroup(DBlue_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(organizer_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(organizer_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(organizer_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(organizer_poster, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(organzier_viewstudents, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DBlue_panel1Layout.setVerticalGroup(
            DBlue_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DBlue_panel1Layout.createSequentialGroup()
                .addGroup(DBlue_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DBlue_panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DBlue_panel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(organizer_new)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(organizer_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(organizer_delete)
                        .addGap(63, 63, 63)
                        .addComponent(organizer_poster)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(organzier_viewstudents)
                .addGap(18, 18, 18)
                .addComponent(DBlue_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DBlue_panel.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BISU Campus Event Manager");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create Event");

        DBlue_panel3.setBackground(new java.awt.Color(130, 130, 146));

        createEvent_title.setBackground(new java.awt.Color(0, 0, 0));
        createEvent_title.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createEvent_title.setForeground(new java.awt.Color(255, 255, 255));
        createEvent_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEvent_titleActionPerformed(evt);
            }
        });

        createEvent_location.setBackground(new java.awt.Color(0, 0, 0));
        createEvent_location.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createEvent_location.setForeground(new java.awt.Color(255, 255, 255));
        createEvent_location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEvent_locationActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Event title:");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Location:");

        createEvent_category.setBackground(new java.awt.Color(255, 255, 255));
        createEvent_category.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createEvent_category.setForeground(new java.awt.Color(0, 0, 0));
        createEvent_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Academic", "Cultural", "Sports & Fitness", "Student Engagement", "Tech & Innovation", "Social Impact", "Professional Development" }));
        createEvent_category.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createEvent_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEvent_categoryActionPerformed(evt);
            }
        });

        createEvent_type.setBackground(new java.awt.Color(255, 255, 255));
        createEvent_type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createEvent_type.setForeground(new java.awt.Color(0, 0, 0));
        createEvent_type.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Category:");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Type:");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Date/Time:");

        createEvent_submit.setBackground(new java.awt.Color(51, 102, 0));
        createEvent_submit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createEvent_submit.setForeground(new java.awt.Color(255, 255, 255));
        createEvent_submit.setText("SUBMIT");
        createEvent_submit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        createEvent_cancel.setBackground(new java.awt.Color(102, 0, 0));
        createEvent_cancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createEvent_cancel.setForeground(new java.awt.Color(255, 255, 255));
        createEvent_cancel.setText("CANCEL");
        createEvent_cancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createEvent_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEvent_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DBlue_panel3Layout = new javax.swing.GroupLayout(DBlue_panel3);
        DBlue_panel3.setLayout(DBlue_panel3Layout);
        DBlue_panel3Layout.setHorizontalGroup(
            DBlue_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DBlue_panel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(DBlue_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DBlue_panel3Layout.createSequentialGroup()
                        .addGroup(DBlue_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(DBlue_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)))
                        .addGroup(DBlue_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DBlue_panel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(DBlue_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(createEvent_title, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                    .addComponent(createEvent_location)))
                            .addGroup(DBlue_panel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(DBlue_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(createEvent_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(createEvent_category, 0, 256, Short.MAX_VALUE)))))
                    .addGroup(DBlue_panel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(DBlue_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DBlue_panel3Layout.createSequentialGroup()
                                .addComponent(createEvent_submit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createEvent_cancel))
                            .addComponent(createEvent_dateTime))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        DBlue_panel3Layout.setVerticalGroup(
            DBlue_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DBlue_panel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(DBlue_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEvent_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(DBlue_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEvent_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(DBlue_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(createEvent_category, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DBlue_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(createEvent_type, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DBlue_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(createEvent_dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DBlue_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEvent_submit)
                    .addComponent(createEvent_cancel))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DBlue_panelLayout = new javax.swing.GroupLayout(DBlue_panel);
        DBlue_panel.setLayout(DBlue_panelLayout);
        DBlue_panelLayout.setHorizontalGroup(
            DBlue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DBlue_panelLayout.createSequentialGroup()
                .addGroup(DBlue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DBlue_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DBlue_panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DBlue_panelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(DBlue_panelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DBlue_panelLayout.setVerticalGroup(
            DBlue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DBlue_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(DBlue_panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        getContentPane().add(DBlue_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createEvent_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEvent_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createEvent_titleActionPerformed

    private void createEvent_locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEvent_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createEvent_locationActionPerformed

    private void createEvent_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEvent_cancelActionPerformed
        adminDashboard.main(args);
        dispose();
    }//GEN-LAST:event_createEvent_cancelActionPerformed

    private void createEvent_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEvent_categoryActionPerformed
       
        
    }//GEN-LAST:event_createEvent_categoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DBlue_panel;
    private javax.swing.JPanel DBlue_panel1;
    private javax.swing.JPanel DBlue_panel2;
    private javax.swing.JPanel DBlue_panel3;
    private javax.swing.JButton createEvent_cancel;
    private javax.swing.JComboBox<String> createEvent_category;
    private javax.swing.JSpinner createEvent_dateTime;
    private javax.swing.JTextField createEvent_location;
    private javax.swing.JButton createEvent_submit;
    private javax.swing.JTextField createEvent_title;
    private javax.swing.JComboBox<String> createEvent_type;
    private javax.swing.JTable event_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton organizer_delete;
    private javax.swing.JButton organizer_edit;
    private javax.swing.JButton organizer_new;
    private javax.swing.JButton organizer_poster;
    private javax.swing.JButton organzier_viewstudents;
    // End of variables declaration//GEN-END:variables
}
