/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package first_design_final_project_1;

/**
 *
 * @author PC
 */
public class OrganizerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Organizer_Dashboard_Admin
     */
    public OrganizerDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DBlue_panel1 = new javax.swing.JPanel();
        DBlue_panel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        event_table = new javax.swing.JTable();
        organizer_new = new javax.swing.JButton();
        organizer_edit = new javax.swing.JButton();
        organizer_delete = new javax.swing.JButton();
        organzier_viewstudents = new javax.swing.JButton();
        registerEvent_user1 = new javax.swing.JButton();
        DBlue_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DBlue_panel1.setBackground(new java.awt.Color(98, 98, 130));

        DBlue_panel2.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout DBlue_panel2Layout = new javax.swing.GroupLayout(DBlue_panel2);
        DBlue_panel2.setLayout(DBlue_panel2Layout);
        DBlue_panel2Layout.setHorizontalGroup(
            DBlue_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );
        DBlue_panel2Layout.setVerticalGroup(
            DBlue_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        event_table.setAutoCreateRowSorter(true);
        event_table.setBackground(new java.awt.Color(20, 20, 20));
        event_table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        event_table.setForeground(new java.awt.Color(51, 51, 51));
        event_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Events", "Event type", "Location", "Date & Time: Begin/End", "Participants"
            }
        ));
        event_table.setFocusable(false);
        event_table.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(event_table);

        organizer_new.setBackground(new java.awt.Color(37, 55, 30));
        organizer_new.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        organizer_new.setForeground(new java.awt.Color(255, 255, 255));
        organizer_new.setText("Create new event");
        organizer_new.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        organizer_edit.setBackground(new java.awt.Color(37, 55, 30));
        organizer_edit.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        organizer_edit.setForeground(new java.awt.Color(255, 255, 255));
        organizer_edit.setText("Edit event");
        organizer_edit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        organizer_delete.setBackground(new java.awt.Color(51, 0, 0));
        organizer_delete.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        organizer_delete.setForeground(new java.awt.Color(255, 255, 255));
        organizer_delete.setText("Delete event");
        organizer_delete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        organzier_viewstudents.setBackground(new java.awt.Color(102, 51, 0));
        organzier_viewstudents.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        organzier_viewstudents.setForeground(new java.awt.Color(255, 255, 255));
        organzier_viewstudents.setText("View registered users");
        organzier_viewstudents.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        registerEvent_user1.setBackground(new java.awt.Color(51, 0, 0));
        registerEvent_user1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        registerEvent_user1.setForeground(new java.awt.Color(255, 255, 255));
        registerEvent_user1.setText("Log out");
        registerEvent_user1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout DBlue_panel1Layout = new javax.swing.GroupLayout(DBlue_panel1);
        DBlue_panel1.setLayout(DBlue_panel1Layout);
        DBlue_panel1Layout.setHorizontalGroup(
            DBlue_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DBlue_panel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(DBlue_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DBlue_panel1Layout.createSequentialGroup()
                        .addGroup(DBlue_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(organizer_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(organizer_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(organizer_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DBlue_panel1Layout.createSequentialGroup()
                        .addComponent(organzier_viewstudents, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registerEvent_user1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(DBlue_panel1Layout.createSequentialGroup()
                .addComponent(DBlue_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        DBlue_panel1Layout.setVerticalGroup(
            DBlue_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DBlue_panel1Layout.createSequentialGroup()
                .addGroup(DBlue_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DBlue_panel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(organizer_new)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(organizer_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(organizer_delete))
                    .addGroup(DBlue_panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(DBlue_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerEvent_user1)
                    .addComponent(organzier_viewstudents))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(DBlue_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(DBlue_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 950, 430));

        DBlue_panel.setBackground(new java.awt.Color(0, 0, 51));
        DBlue_panel.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BISU Campus Event Manager");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Event Organizer Dashboard");

        javax.swing.GroupLayout DBlue_panelLayout = new javax.swing.GroupLayout(DBlue_panel);
        DBlue_panel.setLayout(DBlue_panelLayout);
        DBlue_panelLayout.setHorizontalGroup(
            DBlue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DBlue_panelLayout.createSequentialGroup()
                .addGroup(DBlue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DBlue_panelLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel1))
                    .addGroup(DBlue_panelLayout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel2)))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        DBlue_panelLayout.setVerticalGroup(
            DBlue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DBlue_panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(DBlue_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrganizerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrganizerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrganizerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrganizerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrganizerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DBlue_panel;
    private javax.swing.JPanel DBlue_panel1;
    private javax.swing.JPanel DBlue_panel2;
    private javax.swing.JTable event_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton organizer_delete;
    private javax.swing.JButton organizer_edit;
    private javax.swing.JButton organizer_new;
    private javax.swing.JButton organzier_viewstudents;
    private javax.swing.JButton registerEvent_user1;
    // End of variables declaration//GEN-END:variables
}
