/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package first_design_final_project_1;

/**
 *
 * @author PC
 */
public class Register_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Register_Frame_new
     */
    public Register_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        DBlue_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        White_panel = new javax.swing.JPanel();
        register_name = new javax.swing.JTextField();
        register_password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        register_email = new javax.swing.JTextField();
        register_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Register_submit = new javax.swing.JButton();
        Register_cancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Cbox_role = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        rbutton_male = new javax.swing.JRadioButton();
        rbutton_female = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        register_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(410, 499));
        setPreferredSize(new java.awt.Dimension(410, 499));
        setResizable(false);
        setSize(new java.awt.Dimension(410, 499));
        getContentPane().setLayout(null);

        DBlue_panel.setBackground(new java.awt.Color(0, 0, 51));
        DBlue_panel.setMaximumSize(new java.awt.Dimension(410, 499));
        DBlue_panel.setMinimumSize(new java.awt.Dimension(410, 499));
        DBlue_panel.setPreferredSize(new java.awt.Dimension(410, 499));
        DBlue_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        jLabel1.setText("BISU Campus Event Manager");
        DBlue_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 25, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel2.setText("Register");
        DBlue_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 59, -1, -1));

        White_panel.setBackground(new java.awt.Color(204, 204, 204));
        White_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register_name.setBackground(new java.awt.Color(0, 0, 0));
        register_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        register_name.setForeground(new java.awt.Color(255, 255, 255));
        register_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_nameActionPerformed(evt);
            }
        });
        White_panel.add(register_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 236, -1));

        register_password.setBackground(new java.awt.Color(0, 0, 0));
        register_password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        register_password.setForeground(new java.awt.Color(255, 255, 255));
        register_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_passwordActionPerformed(evt);
            }
        });
        White_panel.add(register_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 236, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Name:");
        White_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 65, 90, 20));

        register_email.setBackground(new java.awt.Color(0, 0, 0));
        register_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        register_email.setForeground(new java.awt.Color(255, 255, 255));
        register_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_emailActionPerformed(evt);
            }
        });
        White_panel.add(register_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 236, -1));

        register_username.setBackground(new java.awt.Color(0, 0, 0));
        register_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        register_username.setForeground(new java.awt.Color(255, 255, 255));
        register_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_usernameActionPerformed(evt);
            }
        });
        White_panel.add(register_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 236, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email:");
        White_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 95, 90, 20));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Username:");
        White_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 125, 90, 20));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Password:");
        White_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 155, 90, 20));

        Register_submit.setBackground(new java.awt.Color(0, 102, 0));
        Register_submit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Register_submit.setForeground(new java.awt.Color(255, 255, 255));
        Register_submit.setText("SUBMIT");
        Register_submit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        White_panel.add(Register_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        Register_cancel.setBackground(new java.awt.Color(102, 0, 0));
        Register_cancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Register_cancel.setForeground(new java.awt.Color(255, 255, 255));
        Register_cancel.setText("CANCEL");
        Register_cancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        White_panel.add(Register_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Please fill-up the needed information. ");
        White_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Note: Any missing details will be notified by the admins and have it deleted.");
        White_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, -1, -1));

        Cbox_role.setBackground(new java.awt.Color(0, 0, 0));
        Cbox_role.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cbox_role.setForeground(new java.awt.Color(255, 255, 255));
        Cbox_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Faculty Staff", "Admin", "Crew", "Guest" }));
        Cbox_role.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        White_panel.add(Cbox_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 161, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Role:");
        White_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 272, -1, -1));

        genderGroup.add(rbutton_male);
        rbutton_male.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        rbutton_male.setForeground(new java.awt.Color(0, 0, 0));
        rbutton_male.setText("Male");
        rbutton_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutton_maleActionPerformed(evt);
            }
        });
        White_panel.add(rbutton_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 70, -1));

        genderGroup.add(rbutton_female);
        rbutton_female.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        rbutton_female.setForeground(new java.awt.Color(0, 0, 0));
        rbutton_female.setText("Female");
        White_panel.add(rbutton_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("I.D. :");
        White_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, -1));

        register_id.setBackground(new java.awt.Color(0, 0, 0));
        register_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        register_id.setForeground(new java.awt.Color(255, 255, 255));
        register_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_idActionPerformed(evt);
            }
        });
        White_panel.add(register_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 236, -1));

        DBlue_panel.add(White_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 410, 310));

        getContentPane().add(DBlue_panel);
        DBlue_panel.setBounds(0, 0, 410, 499);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void register_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_idActionPerformed

    private void rbutton_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutton_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutton_maleActionPerformed

    private void register_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_usernameActionPerformed

    private void register_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_emailActionPerformed

    private void register_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_passwordActionPerformed

    private void register_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbox_role;
    private javax.swing.JPanel DBlue_panel;
    private javax.swing.JButton Register_cancel;
    private javax.swing.JButton Register_submit;
    private javax.swing.JPanel White_panel;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbutton_female;
    private javax.swing.JRadioButton rbutton_male;
    private javax.swing.JTextField register_email;
    private javax.swing.JTextField register_id;
    private javax.swing.JTextField register_name;
    private javax.swing.JPasswordField register_password;
    private javax.swing.JTextField register_username;
    // End of variables declaration//GEN-END:variables
}
